version: '3'

services:
  users_service:
    build: ./users_service
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=some_db
      - POSTGRES_HOST=users_postgres
      - POSTGRES_PORT=5432
    depends_on:
      - users_postgres
    volumes:
      - ./users_service/:/app/

  users_postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=some_db
    volumes:
      - postgres_users_data:/var/lib/postgresql/data/

volumes:
  postgres_users_data: